version: '2.1'
services:
    core-service:
      build: ./core-service
      restart: on-failure     
      ports: 
          - 8080:8080

    integration-service:
      build: ./integration-service
      restart: on-failure
      ports:
          - 8081:8081

    hero-db:
        image: postgres:9.5
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=hero
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres

volumes:
  db-data: