version: '2'
services:
    core-service:
      build:
       context: core-service
       dockerfile: Dockerfile
      ports: 
          - 8080:8080
      depends_on:
          - db
    db:
        container_name: marvel_db
        image: postgres:9.5
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=marvel
        ports:
            - 5332:5332