version: '2.1'
services:
    core-service:
      build: ./core-service
      restart: on-failure     
      ports: 
          - 8080:8080
          
    db:
        container_name: marvel_db
        image: postgres:9.5
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=marvel
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres

volumes:
  db-data: