version: '2.1'
services:
    core-service:
      build: ./core-service
      restart: on-failure     
      ports:
          - 8083:8083

    integration-service:
      build: ./integration-service
      restart: on-failure
      ports:
          - 8081:8081

    simulation-service:
      build: ./simulation-service
      restart: on-failure
      ports:
        - 8082:8082

    discovery-server:
      build: ./discovery-server
      restart: on-failure
      ports:
        - 8761:8761

    config-server:
      build: ./config-server
      restart: on-failure
      ports:
        - 8888:8888

    gateway-edge-server:
      build: ./gateway-edge-server
      restart: on-failure
      ports:
        - 8060:8060

    hero-db:
        image: postgres:9.5
        restart: on-failure
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=hero
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres

volumes:
  db-data: