version: '2.1'
services:
    hero-db:
      image: postgres:9.5
      restart: on-failure
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=hero
      ports:
        - 5432:5432
      volumes:
        - db-data:/var/lib/postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -h hero-db -p 5432 -d hero -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    statistic-db:
      image: mongo:4.2.6
      restart: on-failure
      environment:
        - MONGO_INITDB_ROOT_USERNAME=mongo
        - MONGO_INITDB_ROOT_PASSWORD=mongo
        - MONGO_INITDB_DATABASE=statistic
      ports:
        - 27017:27017
      volumes:
        - db-data:/var/lib/mongo
      healthcheck:
        test: echo 'db.runCommand("ping").ok'
        interval: 10s
        timeout: 5s
        retries: 5

    config-server:
      build: ./config-server
      restart: on-failure
      ports:
        - 8888:8888

    discovery-server:
      build: ./discovery-server
      restart: on-failure
      ports:
        - 8761:8761
      depends_on:
        config-server:
          condition: service_healthy

    gateway-service:
      build: ./gateway-service
      restart: on-failure
      ports:
        - 8060:8060
      depends_on:
        discovery-server:
          condition: service_healthy

    integration-service:
      build: ./integration-service
      restart: on-failure
      ports:
        - 8081:8081
      depends_on:
        discovery-server:
          condition: service_healthy

    simulation-service:
      build: ./simulation-service
      restart: on-failure
      ports:
        - 8082:8082
      depends_on:
        discovery-server:
          condition: service_healthy

    core-service:
      build: ./core-service
      restart: on-failure
      ports:
        - 8083:8083
      depends_on:
        integration-service:
          condition: service_healthy
        hero-db:
          condition: service_healthy

    statistic-service:
      build: ./statistic-service
      restart: on-failure
      ports:
        - 8084:8084
      depends_on:
        statistic-db:
          condition: service_healthy

volumes:
  db-data: