version: '2.1'
services:
    core-service:
      build:
       context: core-service
       dockerfile: Dockerfile
      network_mode: bridge
      ports: 
          - 8080:8080
      depends_on:
          db:
             condition: service_healthy
    db:
        container_name: marvel_db
        image: postgres:9.5
        network_mode: bridge
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "marvel", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=marvel
        expose:
            - 5432
        ports:
            - 5432:5432