version: '3.7'
services:
    core-service:
      build:
       context: core-service
       dockerfile: Dockerfile
      environment: 
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marvel
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres   
      restart: always
      depends_on: 
        - db        
      ports: 
          - 8080:8080
          
    db:
        container_name: marvel_db
        image: postgres:9.5
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=marvel
        expose:
            - 5432
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgres

volumes:
  db-data: