spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/marvel
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yml
