spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hero-db:5432/hero
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yml

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

event:
  listener:
    enabled: true

ui_origin: http://localhost:8060

server:
  port: 8083