eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


zuul:
  routes:
    super-heroes:
      url: http://core-service:8083/super-heroes/
      sensitive-headers: Cookie,Set-Cookie

server:
  port: 8060