server:
  port: 8081


spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

api_key: 1092405501141478
api_url: https://superheroapi.com/api/

management:
  server:
    port: 8091